apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 1.6.4
  values:
    meshProvider: istio
    metricsServer: http://prometheus.monitoring:9090
